# Generated by Django 3.1.7 on 2022-05-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220505_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='subscription',
            new_name='topic',
        ),
    ]
